version: '3.3'

services:
    web:
        image: webdevops/php-apache-dev:7.4
        container_name: phpexercises
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=local.domain.com
          - WEB_DOCUMENT_ROOT=/app
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
          - PHP_EXTENSION_XDEBUG=1
        volumes:
            - ./:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
volumes:
    db-data:
        external: false
